services:
  tika:
    image: apache/tika:3.3.1.0-full
    ports:
      - 9998:9998
    restart: unless-stopped

  mango:
    image: mango-sodar:latest
    build: .
    restart: unless-stopped
    network_mode: host
    environment:
      DEBUG: true
      MANGO_AUTH: "login"
      IRODS_HOST: $IRODS_HOST
      SECRET_KEY: $MANGO_SECRET_KEY
      TIKA_URL: "http://localhost:9998"
    volumes:
      - type: bind  # Traefik configuration for shared certs
        source: $IRODS_SSL_CA_CERTIFICATE_PATH
        target: /etc/traefik/tls/server.crt
      - type: bind  # Mount local files
        source: ./src
        target: /app
